/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Oscar Torres
 */
public class HoyNoCirculaGraf extends javax.swing.JFrame {

    /**
     * Creates new form HoyNoCirculaGraf
     */
    public HoyNoCirculaGraf() {
        initComponents();
        cbplaca.removeAllItems();
        cbdia.removeAllItems();
        cbcolor.removeAllItems();
        cbplaca.addItem("0");
         cbplaca.addItem("1");
          cbplaca.addItem("2");
           cbplaca.addItem("3");
            cbplaca.addItem("4");
             cbplaca.addItem("5");
              cbplaca.addItem("6");
               cbplaca.addItem("7");
                cbplaca.addItem("8");
                 cbplaca.addItem("9");
                 cbcolor.addItem("amarillo");
                 cbcolor.addItem("rosa");
                 cbcolor.addItem("rojo");
                 cbcolor.addItem("verde");
                 cbcolor.addItem("azul");
                 cbdia.addItem("lunes");
                 cbdia.addItem("martes");
                 cbdia.addItem("miercoles");
                 cbdia.addItem("jueves");
                 cbdia.addItem("viernes");
                 cbdia.addItem(" ");
                 cbcolor.addItem(" ");
                 cbplaca.addItem(" ");
                 
                 revisar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String u1 =(String) cbplaca.getSelectedItem();
                String u2 =(String) cbcolor.getSelectedItem();
                String u3 =(String) cbdia.getSelectedItem();
                NoCircula NC = new NoCircula();
                if(u1== " " &&  u2== " " && u3!= " ")
                {
                  String imp = NC.getTerminacion(u3);
                  imprimirtxt.setText(imp);
                   
                }
                if(u1== " " &&  u2!= " " && u3== " "){
                    String imp = NC.getColor(u2);
                  imprimirtxt.setText(imp);
                   
                }
                if(u1!= " " &&  u2== " " && u3== " "){
                    String imp = NC.getByPlaca(u1);
                  imprimirtxt.setText(imp);
                }
                         
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbplaca = new javax.swing.JComboBox<>();
        cbdia = new javax.swing.JComboBox<>();
        cbcolor = new javax.swing.JComboBox<>();
        imprimirtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        revisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbplaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imprimirtxt.setText("jTextField1");

        jButton1.setText("jButton1");

        revisar.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbplaca, 0, 146, Short.MAX_VALUE)
                    .addComponent(cbdia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbcolor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imprimirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(revisar)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revisar))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoyNoCirculaGraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcolor;
    private javax.swing.JComboBox<String> cbdia;
    private javax.swing.JComboBox<String> cbplaca;
    private javax.swing.JTextField imprimirtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton revisar;
    // End of variables declaration//GEN-END:variables
}
